--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 10.5

-- Started on 2018-10-27 23:03:24 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 1 (class 3079 OID 13005)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2985 (class 0 OID 0)
-- Dependencies: 1
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 16386)
-- Name: analysis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis (
    id integer NOT NULL,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    description text
);


--
-- TOC entry 197 (class 1259 OID 16392)
-- Name: analysis_diagnosis_rel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analysis_diagnosis_rel (
    id integer NOT NULL,
    analysis_id integer NOT NULL,
    diagnosis_id integer NOT NULL
);


--
-- TOC entry 212 (class 1259 OID 24617)
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    body text
);


--
-- TOC entry 211 (class 1259 OID 24615)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.articles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2986 (class 0 OID 0)
-- Dependencies: 211
-- Name: articles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.articles_id_seq OWNED BY public.articles.id;


--
-- TOC entry 198 (class 1259 OID 16395)
-- Name: diagnosis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diagnosis (
    id integer NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    description text,
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL
);


--
-- TOC entry 208 (class 1259 OID 24603)
-- Name: diagnosis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.diagnosis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2987 (class 0 OID 0)
-- Dependencies: 208
-- Name: diagnosis_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.diagnosis_id_seq OWNED BY public.diagnosis.id;


--
-- TOC entry 199 (class 1259 OID 16401)
-- Name: drug_relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drug_relations (
    id integer,
    drug_id_1 integer NOT NULL,
    drug_id_2 integer NOT NULL,
    drug_relation_type integer NOT NULL,
    description text
);


--
-- TOC entry 200 (class 1259 OID 16407)
-- Name: drugs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drugs (
    id integer,
    description text,
    name character varying(255),
    active_ingridient character varying(255),
    contradictions character varying(255),
    side_effects text
);


--
-- TOC entry 201 (class 1259 OID 16413)
-- Name: event_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_types (
    id integer NOT NULL,
    title character varying(255)
);


--
-- TOC entry 202 (class 1259 OID 16416)
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    drug_id integer,
    event_date timestamp without time zone,
    treatment_id integer,
    event_type character varying(255),
    analysis character varying(255)
);


--
-- TOC entry 210 (class 1259 OID 24609)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2988 (class 0 OID 0)
-- Dependencies: 210
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- TOC entry 203 (class 1259 OID 16420)
-- Name: patient_drug_restrictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patient_drug_restrictions (
    id integer NOT NULL,
    patient_id integer NOT NULL,
    restricted_drug_id integer NOT NULL,
    description text
);


--
-- TOC entry 204 (class 1259 OID 16426)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    description character varying(255)
);


--
-- TOC entry 205 (class 1259 OID 16429)
-- Name: treatments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treatments (
    id integer NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    doctor_id integer NOT NULL,
    diagnosis_id integer NOT NULL
);


--
-- TOC entry 209 (class 1259 OID 24606)
-- Name: treatments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.treatments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 2989 (class 0 OID 0)
-- Dependencies: 209
-- Name: treatments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.treatments_id_seq OWNED BY public.treatments.id;


--
-- TOC entry 207 (class 1259 OID 24577)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 206 (class 1259 OID 16432)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    username character varying(255),
    password character varying(255),
    role character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    id integer DEFAULT nextval('public.users_id_seq'::regclass) NOT NULL,
    token character varying(255)
);


--
-- TOC entry 2815 (class 2604 OID 24620)
-- Name: articles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles ALTER COLUMN id SET DEFAULT nextval('public.articles_id_seq'::regclass);


--
-- TOC entry 2811 (class 2604 OID 24605)
-- Name: diagnosis id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis ALTER COLUMN id SET DEFAULT nextval('public.diagnosis_id_seq'::regclass);


--
-- TOC entry 2812 (class 2604 OID 24611)
-- Name: events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- TOC entry 2813 (class 2604 OID 24608)
-- Name: treatments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments ALTER COLUMN id SET DEFAULT nextval('public.treatments_id_seq'::regclass);


--
-- TOC entry 2961 (class 0 OID 16386)
-- Dependencies: 196
-- Data for Name: analysis; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.analysis (id, patient_id, doctor_id, description) FROM stdin;
\.


--
-- TOC entry 2962 (class 0 OID 16392)
-- Dependencies: 197
-- Data for Name: analysis_diagnosis_rel; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.analysis_diagnosis_rel (id, analysis_id, diagnosis_id) FROM stdin;
\.


--
-- TOC entry 2977 (class 0 OID 24617)
-- Dependencies: 212
-- Data for Name: articles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.articles (id, title, description, body) FROM stdin;
\.


--
-- TOC entry 2963 (class 0 OID 16395)
-- Dependencies: 198
-- Data for Name: diagnosis; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.diagnosis (id, start_date, end_date, description, patient_id, doctor_id) FROM stdin;
2	2018-10-16 13:00:00	\N	influenza	2	4
1	2018-09-10 18:00:00	\N	asthma	1	4
\.


--
-- TOC entry 2964 (class 0 OID 16401)
-- Dependencies: 199
-- Data for Name: drug_relations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.drug_relations (id, drug_id_1, drug_id_2, drug_relation_type, description) FROM stdin;
\.


--
-- TOC entry 2965 (class 0 OID 16407)
-- Dependencies: 200
-- Data for Name: drugs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.drugs (id, description, name, active_ingridient, contradictions, side_effects) FROM stdin;
\N	Albuterol (also known as salbutamol) is used to prevent and treat wheezing and shortness of breath caused by breathing problems (such as asthma, chronic obstructive pulmonary disease). It is also used to prevent asthma brought on by exercise. It is a quick-relief drug. Albuterol belongs to a class of drugs known as bronchodilators. It works in the airways by opening breathing passages and relaxing muscles. Controlling symptoms of breathing problems can decrease time lost from work or school.	Ventolin	Salbutamol Sulphate	\N	Muscle cramps, Increased heart rate, Tremor/shakes, Headaches
\.


--
-- TOC entry 2966 (class 0 OID 16413)
-- Dependencies: 201
-- Data for Name: event_types; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.event_types (id, title) FROM stdin;
1	take_medicine
2	visit_doctor
3	do_analysis
\.


--
-- TOC entry 2967 (class 0 OID 16416)
-- Dependencies: 202
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.events (id, drug_id, event_date, treatment_id, event_type, analysis) FROM stdin;
2	\N	\N	1	analysis	photofluorography
3	1	\N	1	medicine	\N
4	\N	\N	2	analysis	blood
5	3	\N	2	medicine	\N
\.


--
-- TOC entry 2968 (class 0 OID 16420)
-- Dependencies: 203
-- Data for Name: patient_drug_restrictions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.patient_drug_restrictions (id, patient_id, restricted_drug_id, description) FROM stdin;
\.


--
-- TOC entry 2969 (class 0 OID 16426)
-- Dependencies: 204
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (id, description) FROM stdin;
1	patient
2	doctor
\.


--
-- TOC entry 2970 (class 0 OID 16429)
-- Dependencies: 205
-- Data for Name: treatments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.treatments (id, start_date, end_date, doctor_id, diagnosis_id) FROM stdin;
1	2018-09-10 18:00:00	\N	4	1
2	2018-10-16 13:00:00	\N	4	2
\.


--
-- TOC entry 2971 (class 0 OID 16432)
-- Dependencies: 206
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (username, password, role, first_name, last_name, id, token) FROM stdin;
willy	123	patient	William	Brown	3	\N
oliver_brown_1976	123	patient	Oliver	Brown	2	
leila_s	123	patient	Leila	Smith	1	\N
j_williams	123	doctor	James	Williams	4	
123	123	123	123	123	5	123
acerikfy	123	patient	nikita	orlov	6	a1a0e961-aef9-4cc0-bf6f-f26725fd010c
\.


--
-- TOC entry 2990 (class 0 OID 0)
-- Dependencies: 211
-- Name: articles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.articles_id_seq', 1, false);


--
-- TOC entry 2991 (class 0 OID 0)
-- Dependencies: 208
-- Name: diagnosis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.diagnosis_id_seq', 2, true);


--
-- TOC entry 2992 (class 0 OID 0)
-- Dependencies: 210
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.events_id_seq', 5, true);


--
-- TOC entry 2993 (class 0 OID 0)
-- Dependencies: 209
-- Name: treatments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.treatments_id_seq', 2, true);


--
-- TOC entry 2994 (class 0 OID 0)
-- Dependencies: 207
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 23, true);


--
-- TOC entry 2819 (class 2606 OID 16439)
-- Name: analysis_diagnosis_rel analysis_diagnosis_rel_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis_diagnosis_rel
    ADD CONSTRAINT analysis_diagnosis_rel_id_key UNIQUE (id);


--
-- TOC entry 2817 (class 2606 OID 16441)
-- Name: analysis analysis_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analysis
    ADD CONSTRAINT analysis_id_key UNIQUE (id);


--
-- TOC entry 2839 (class 2606 OID 24625)
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- TOC entry 2821 (class 2606 OID 16445)
-- Name: drug_relations drug_relations_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drug_relations
    ADD CONSTRAINT drug_relations_id_key UNIQUE (id);


--
-- TOC entry 2823 (class 2606 OID 16447)
-- Name: drugs drugs_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drugs
    ADD CONSTRAINT drugs_id_key UNIQUE (id);


--
-- TOC entry 2825 (class 2606 OID 16449)
-- Name: event_types event_types_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_types
    ADD CONSTRAINT event_types_id_key UNIQUE (id);


--
-- TOC entry 2827 (class 2606 OID 16451)
-- Name: events events_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_id_key UNIQUE (id);


--
-- TOC entry 2829 (class 2606 OID 16453)
-- Name: patient_drug_restrictions patient_drug_restrictions_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patient_drug_restrictions
    ADD CONSTRAINT patient_drug_restrictions_id_key UNIQUE (id);


--
-- TOC entry 2831 (class 2606 OID 16455)
-- Name: roles roles_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_id_key UNIQUE (id);


--
-- TOC entry 2833 (class 2606 OID 16457)
-- Name: treatments treatments_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments
    ADD CONSTRAINT treatments_id_key UNIQUE (id);


--
-- TOC entry 2835 (class 2606 OID 16459)
-- Name: users users_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_key UNIQUE (id);


--
-- TOC entry 2837 (class 2606 OID 24581)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


-- Completed on 2018-10-27 23:03:25 MSK

--
-- PostgreSQL database dump complete
--

