# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DynaCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for DynaCare
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'paper-onboarding'
  pod "ScalingCarousel"
  pod "ScrollingStackViewController"
  pod 'HexColors', '~> 2.3'
  pod "MarkdownView"
  pod "TimelineTableViewCell"
  pod 'Kingfisher', '~> 4.0'
end
